### ISSUE TITLE
Kronecker delta symbols don't commute

### ISSUE THREAD

**Issue by Kiseliov** [rokzitko/nrgljubljana-old#1]
Hello, 
It seems that it suppose that delta symbols don't commute with the operators and thus stuck at intermediate stages of calculation when such a situation appears. SnegSimplify and SnegFullSimplify.
![delta](https://github.com/rokzitko/nrgljubljana-old/assets/34189964/e3676344-5ee5-44fb-9ece-0cb01d2c89fd)

**Comment by Kiseliov** [comment]
Sorry accidentally pressed. Simplify functions don't seem to work.

**Comment by rokzitko** [comment]
Hi,
You should declare the variables x1, z1, etc. to be constants (i.e., non-operators) using snegrealconstatns[x1,z1,...] or similar sneg declaration functions.
Rok

**Comment by Kiseliov** [comment]
Thank you, sorry just noticed that put it in the wrong project.
Thanks again
